lantern/django/django_intro/src/apps/articles/urls.py
from django.urls import path

from apps.articles.views import main_page, SearchResultsView

app_name = 'articles'

urlpatterns = [
    path('search/', main_page, name='main-page'),
    path('results/', SearchResultsView.as_view(), name='search-results')
]

lantern/django/django_intro/src/config/urls.py
"""django_intro URL Configuration

The `urlpatterns` list routes URLs to routes. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function routes
    1. Add an import:  from my_app import routes
    2. Add a URL to urlpatterns:  path('', routes.home, name='home')
Class-based routes
    1. Add an import:  from other_app.routes import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('apps.articles.urls', namespace='articles'))
]

lantern/django/django_intro/src/apps/articles/models.py
from django.conf import settings
from django.db import models


# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=40, unique=True)


class Article(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    title = models.CharField(max_length=255, verbose_name='Title', db_index=True)
    body = models.TextField(max_length=5000, verbose_name='Article body')
    tags = models.ManyToManyField(to='Tag', related_name='articles', blank=True)
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        related_name='articles'
    )

lantern/django/django_intro/src/apps/articles/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(required=False)

lantern/django/django_intro/src/apps/articles/views.py
from django.shortcuts import render
# Create your routes here.
from django.views import View

from apps.articles.forms import SearchForm
from apps.articles.models import Article


def main_page(request):
    return render(request, 'pages/main_page.html')


class SearchResultsView(View):
    def get(self, request, **kwargs):
        # form = SearchForm(data=request.GET)
        search_q = request.GET.get('search', '')
        if search_q:
            articles = Article.objects.filter(title__icontains=search_q)
        else:
            articles = Article.objects.all()

        context_data = {
            'articles': articles,
            # 'search_form': form
        }
        return render(request, 'pages/search.html', context=context_data)

lantern/django/django_intro/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <style>
    .search-block {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 80vh;
    }

    .search-block h1 {
      text-align: center;
    }

    .article-list {

    }

    .article {
      border: 1px solid #cccccc;
      padding: 5px;
      margin: 10px;
    }

    article h3 {
      font-weight: bold;
    }
  </style>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

lantern/django/django_intro/src/templates/pages/main_page.html
{% extends 'base.html' %}

{% block content %}

  <div class="search-block">
    <form action="{% url 'articles:search-results' %}">
      <h1>Google</h1>
      
      <div class="search-input">
        <label>
          <input type="text" name="search" placeholder="Search something ...">
        </label>
        <input type="submit">
      </div>
    </form>
  </div>
{% endblock %}

lantern/django/django_intro/src/templates/pages/search.html
{% extends 'base.html' %}

{% block content %}
  <h2 style="text-align: center">We found something for you :)</h2>
  <div class="article-list">
    {% for article in articles %}
      <div class="article">
        <h3>{{ article.title }}</h3>
        <p>{{ article.body|slice:":160" }}...</p>
      </div>
    {% endfor %}
  </div>

{% endblock %}