lantern/flask/flask_login_and_templates/practice/grocery_store/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from grocery_store.database import db
from grocery_store.models import User
from flask_login import login_user, login_required, logout_user

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    return render_template("login.html")


@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if user actually exists
    # take the user supplied password, hash it, and compare it to the hashed password in database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if user doesn't exist or password is wrong, reload the page

    login_user(user, remember=remember)
    # if the above check passes, then we know the user has the right credentials
    # login code goes here
    return redirect(url_for('main.profile'))


@auth.route('/signup')
def signup():
    return render_template("signup.html")


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    # if this returns a user, then the email already exists in database
    user = User.query.filter_by(email=email).first()

    # if a user is found, we want to redirect back to signup page so user can try again
    if user:
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    # create new user with the form data. Hash the password so plaintext version isn't saved.
    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for("auth.login"))

lantern/flask/flask_login_and_templates/practice/grocery_store/routes/main.py
from flask import Blueprint, render_template
from grocery_store.database import db
from flask_login import current_user, login_required

from grocery_store.models import Good


main = Blueprint('main', __name__)


@main.route('/')
def index():
    goods = Good.query.all()
    return render_template('index.html', goods=goods)


@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', user=current_user.name, email=current_user.email)


@main.route('/order')
@login_required
def order():
    user = current_user.name
    email = current_user.email
    orders = current_user.orders

    # sum of all user goods price / output user goods
    for ordering in orders:
        # import pdb;pdb.set_trace()
        full_price = sum([order_lin.good.price for order_lin in ordering.order_lines])
        goods_price = [order_lin.good.price for order_lin in ordering.order_lines]
        goods_name = [order_lin.good.name for order_lin in ordering.order_lines]
    total = full_price
    price = goods_price
    goods = goods_name

    return render_template("order.html", user=user, email=email,
                           orders=orders, total=total, goods=goods, price=price)

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Base{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.order') }}" class="navbar-item">
                                Orders
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated%}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated%}
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block content %}


<h1 class="title">
  Goods list
</h1>

    <table align="center">
    <h2 class="subtitle">

        <tr>
            <th style="border: 2px solid black;">Name</th>
            {% if current_user.is_authenticated %}
            <th style="border: 2px solid black;">Brand</th>
            {% endif %}
            <th style="border: 2px solid black;">Price</th>
        </tr>

        <tr>
            {% for good in goods %}
            <td style="border: 2px solid #000000; color: black">{{ good.name }}</td>
            {% if current_user.is_authenticated %}
            <td style="border: 2px solid black; color: black">{{ good.brand }}</td>
            {% endif %}
            <td style="border: 2px solid black; color: black">{{ good.price }}</td>
        </tr>

    </h2>
        {% endfor %}
    </table>
{% endblock %}

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/login.html
{% extends "base.html" %}

{% block title %}LOGIN PAGE{% endblock %}


{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="notification is-danger">
        {{ messages[0] }}
      </div>
      {% endif %}
      {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/order.html
{% extends "base.html" %}

{% block title %}Order{% endblock %}

{% block content %}


<h1 class="title">
    <p>Orders</p>
</h1>

    <table>

        <h2  class="subtitle">

            <tr>

                <p>Your name: {{ user }}.</p>

                <p>Email: {{ email }}. </p>

                {% for prices in price %}
                    Price: {{ prices }}
                {% endfor %}


                {% for good in goods %}
                    <p>Orders: {{ good }}. </p>
                {% endfor %}

                <p>Total price: {{ total }}</p>


            </tr>

        </h2>

    </table>

{% endblock %}

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
<h1 class="title">

  <p>Welcome, {{ user }} ! </p>
  <p>Your email: {{ email }} </p>

</h1>
{% endblock %}

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
      <!-- Flashed messages area -->
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="notification is-danger">
        {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
      </div>
      {% endif %}
      {% endwith %}
      <!-- End of flashed messages area -->
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}